[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.2.1",
    "langchain-pinecone>=0.2.13",
    "langchainhub>=0.1.21",
    "mypy>=1.20.2",
    "pypdf>=6.10.2",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.12",
]
